### ISSUE TITLE
How do you install this? A step by step instruction would be very helpful.

### ISSUE THREAD

**Issue by Sehgal-Arjun** [DariuszMusielak/osx-touchbar-parrots-on-steroids#6]

**Comment by DariuszMusielak** [comment]
@Arjun78910 in a Readme there is a section [Installation](https://github.com/DariuszMusielak/osx-touchbar-parrots-on-steroids#installation). I've just checked if it works, everything seems to be fine.

Do you have any issues with it?

**Comment by helpmeplease2787** [comment]
Could you be more specific? Where do we put npm install?

**Comment by DariuszMusielak** [comment]
@helpmeplease2787:
1. Git clone repository
2. Enter the project directory
3. Run in the project directory: npm install. 

Here is an [instruction](https://github.com/DariuszMusielak/osx-touchbar-parrots-on-steroids#installation). What isn't working for you?

**Comment by DariuszMusielak** [comment]
Closing this one since no response from reporter.
